package sc.common.model.queries;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;

import sc.common.model.queries.common.ReportSetupDetailEOVORow;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Mar 14 21:31:58 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ReportSetupDetailEOVORowImpl extends ViewRowImpl implements ReportSetupDetailEOVORow {

    public static final int ENTITY_REPORTSETUPDETAILEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        EiRepDtlId,
        EiRepHeaderId,
        ParamName,
        ParamSqlType,
        DefualtVal,
        LastValLookupType,
        CreatedBy,
        CreatedDate,
        UpdatedBy,
        UpdatedDate,
        SqlStatement;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int EIREPDTLID = AttributesEnum.EiRepDtlId.index();
    public static final int EIREPHEADERID = AttributesEnum.EiRepHeaderId.index();
    public static final int PARAMNAME = AttributesEnum.ParamName.index();
    public static final int PARAMSQLTYPE = AttributesEnum.ParamSqlType.index();
    public static final int DEFUALTVAL = AttributesEnum.DefualtVal.index();
    public static final int LASTVALLOOKUPTYPE = AttributesEnum.LastValLookupType.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int UPDATEDBY = AttributesEnum.UpdatedBy.index();
    public static final int UPDATEDDATE = AttributesEnum.UpdatedDate.index();
    public static final int SQLSTATEMENT = AttributesEnum.SqlStatement.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ReportSetupDetailEOVORowImpl() {
    }

    /**
     * Gets ReportSetupDetailEO entity object.
     * @return the ReportSetupDetailEO
     */
    public EntityImpl getReportSetupDetailEO() {
        return (EntityImpl) getEntity(ENTITY_REPORTSETUPDETAILEO);
    }

    /**
     * Gets the attribute value for EI_REP_DTL_ID using the alias name EiRepDtlId.
     * @return the EI_REP_DTL_ID
     */
    public BigDecimal getEiRepDtlId() {
        return (BigDecimal) getAttributeInternal(EIREPDTLID);
    }

    /**
     * Sets <code>value</code> as attribute value for EI_REP_DTL_ID using the alias name EiRepDtlId.
     * @param value value to set the EI_REP_DTL_ID
     */
    public void setEiRepDtlId(BigDecimal value) {
        setAttributeInternal(EIREPDTLID, value);
    }

    /**
     * Gets the attribute value for EI_REP_HEADER_ID using the alias name EiRepHeaderId.
     * @return the EI_REP_HEADER_ID
     */
    public BigDecimal getEiRepHeaderId() {
        return (BigDecimal) getAttributeInternal(EIREPHEADERID);
    }

    /**
     * Sets <code>value</code> as attribute value for EI_REP_HEADER_ID using the alias name EiRepHeaderId.
     * @param value value to set the EI_REP_HEADER_ID
     */
    public void setEiRepHeaderId(BigDecimal value) {
        setAttributeInternal(EIREPHEADERID, value);
    }

    /**
     * Gets the attribute value for PARAM_NAME using the alias name ParamName.
     * @return the PARAM_NAME
     */
    public String getParamName() {
        return (String) getAttributeInternal(PARAMNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for PARAM_NAME using the alias name ParamName.
     * @param value value to set the PARAM_NAME
     */
    public void setParamName(String value) {
        setAttributeInternal(PARAMNAME, value);
    }

    /**
     * Gets the attribute value for PARAM_SQL_TYPE using the alias name ParamSqlType.
     * @return the PARAM_SQL_TYPE
     */
    public String getParamSqlType() {
        return (String) getAttributeInternal(PARAMSQLTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for PARAM_SQL_TYPE using the alias name ParamSqlType.
     * @param value value to set the PARAM_SQL_TYPE
     */
    public void setParamSqlType(String value) {
        setAttributeInternal(PARAMSQLTYPE, value);
    }

    /**
     * Gets the attribute value for DEFUALT_VAL using the alias name DefualtVal.
     * @return the DEFUALT_VAL
     */
    public String getDefualtVal() {
        return (String) getAttributeInternal(DEFUALTVAL);
    }

    /**
     * Sets <code>value</code> as attribute value for DEFUALT_VAL using the alias name DefualtVal.
     * @param value value to set the DEFUALT_VAL
     */
    public void setDefualtVal(String value) {
        setAttributeInternal(DEFUALTVAL, value);
    }

    /**
     * Gets the attribute value for LAST_VAL_LOOKUP_TYPE using the alias name LastValLookupType.
     * @return the LAST_VAL_LOOKUP_TYPE
     */
    public String getLastValLookupType() {
        return (String) getAttributeInternal(LASTVALLOOKUPTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_VAL_LOOKUP_TYPE using the alias name LastValLookupType.
     * @param value value to set the LAST_VAL_LOOKUP_TYPE
     */
    public void setLastValLookupType(String value) {
        setAttributeInternal(LASTVALLOOKUPTYPE, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATED_DATE using the alias name CreatedDate.
     * @return the CREATED_DATE
     */
    public Timestamp getCreatedDate() {
        return (Timestamp) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_DATE using the alias name CreatedDate.
     * @param value value to set the CREATED_DATE
     */
    public void setCreatedDate(Timestamp value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for UPDATED_BY using the alias name UpdatedBy.
     * @return the UPDATED_BY
     */
    public String getUpdatedBy() {
        return (String) getAttributeInternal(UPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for UPDATED_BY using the alias name UpdatedBy.
     * @param value value to set the UPDATED_BY
     */
    public void setUpdatedBy(String value) {
        setAttributeInternal(UPDATEDBY, value);
    }

    /**
     * Gets the attribute value for UPDATED_DATE using the alias name UpdatedDate.
     * @return the UPDATED_DATE
     */
    public Timestamp getUpdatedDate() {
        return (Timestamp) getAttributeInternal(UPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for UPDATED_DATE using the alias name UpdatedDate.
     * @param value value to set the UPDATED_DATE
     */
    public void setUpdatedDate(Timestamp value) {
        setAttributeInternal(UPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for SQL_STATEMENT using the alias name SqlStatement.
     * @return the SQL_STATEMENT
     */
    public String getSqlStatement() {
        return (String) getAttributeInternal(SQLSTATEMENT);
    }

    /**
     * Sets <code>value</code> as attribute value for SQL_STATEMENT using the alias name SqlStatement.
     * @param value value to set the SQL_STATEMENT
     */
    public void setSqlStatement(String value) {
        setAttributeInternal(SQLSTATEMENT, value);
    }
}

