CREATE SEQUENCE XX_SCH_EXCEPTION_LOG_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE XX_SCH_REPORT_MAP_SEQ START WITH 1 INCREMENT BY 1; 
CREATE SEQUENCE XX_SCH_REPORT_HEADER_SEQ START WITH 1 INCREMENT BY 1; 
CREATE SEQUENCE XX_SCH_SCHEDULER_DATE_SEQ START WITH 1 INCREMENT BY 1; 
CREATE SEQUENCE XX_SCH_SCHEDULER_SETUP_SEQ START WITH 1 INCREMENT BY 1; 
CREATE SEQUENCE XX_SCH_REPORT_RUN_HIST_SEQ START WITH 1 INCREMENT BY 1; 
CREATE SEQUENCE XX_SCH_REPORT_SETUP_DTL_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE XX_SCH_EXCEPTION_LOG
(
  EXCEPTION_ID      NUMBER PRIMARY KEY,
  BEAN_NAME         VARCHAR2(100 BYTE),
  METHOD_NAME       VARCHAR2(100 BYTE),
  ERROR_MESSAGE     CLOB,
  CREATED_DATETIME  TIMESTAMP(6)                DEFAULT SYSDATE,
  CREATED_BY        VARCHAR2(50 BYTE),
  JOB_ID            VARCHAR2(100 CHAR)
);

CREATE TABLE XX_SCH_LOOKUP_STRINGS
(
  GEN_ID       NUMBER PRIMARY KEY,
  TYPE         VARCHAR2(100 BYTE),
  CODE         VARCHAR2(100 BYTE),
  VALUE        VARCHAR2(100 BYTE),
  ENT_DATE     DATE,
  ENT_BY       VARCHAR2(100 BYTE),
  MODIFY_BY    VARCHAR2(100 BYTE),
  MODIFY_DATE  DATE,
  ENABLE_FLAG  VARCHAR2(1 BYTE)
);

CREATE TABLE XX_SCH_REPORT_DATA_MAPPING
(
  MAP_ID            NUMBER(19)                  DEFAULT "XX_SCH_REPORT_MAP_SEQ"."NEXTVAL" NOT NULL,
  REPORT_COL_NAME   VARCHAR2(200 BYTE)          DEFAULT NULL,
  REPORT_SEQ_NAME   NUMBER(10)                  DEFAULT NULL,
  TABLE_COL_NAME    VARCHAR2(200 BYTE)          DEFAULT NULL,
  DEFAULT_VALUE     VARCHAR2(200 BYTE)          DEFAULT NULL,
  REPORT_HEADER_ID  NUMBER(19)                  DEFAULT NULL,
  PRIMARY_FLAG      VARCHAR2(10 BYTE)           DEFAULT NULL,
  DATE_FORMAT       VARCHAR2(50 CHAR),
  IS_SEQ            VARCHAR2(1 BYTE),
  COLUMN_DATA_TYPE  VARCHAR2(200 BYTE),
  CONSTRAINT XX_SCH_REPORT_DATA_MAPPING_PK PRIMARY KEY (MAP_ID)
);

CREATE TABLE XX_SCH_REPORT_RUN_HIS
(
  ID                NUMBER                      NOT NULL,
  SERVICE_TYPE      VARCHAR2(100 CHAR),
  STATUS            VARCHAR2(50 CHAR),
  RECORD_PROCESSED  VARCHAR2(100 CHAR),
  START_TIME        TIMESTAMP(6)                DEFAULT SYSDATE,
  END_TME           TIMESTAMP(6),
  RUN_TYPE          VARCHAR2(50 BYTE),
  SCHEDULER_ID      NUMBER,
  CONSTRAINT XX_SCH_REPORT_RUN_HIS_PK PRIMARY KEY (ID)
);

CREATE TABLE XX_SCH_REPORT_SETUP_DTL
(
  EI_REP_DTL_ID         NUMBER                  NOT NULL,
  EI_REP_HEADER_ID      NUMBER,
  PARAM_NAME            VARCHAR2(50 BYTE),
  PARAM_SQL_TYPE        VARCHAR2(50 BYTE),
  DEFUALT_VAL           VARCHAR2(50 BYTE),
  LAST_VAL_LOOKUP_TYPE  VARCHAR2(50 BYTE),
  CREATED_BY            VARCHAR2(100 BYTE),
  CREATED_DATE          DATE,
  UPDATED_BY            VARCHAR2(100 BYTE),
  UPDATED_DATE          DATE,
  SQL_STATEMENT         VARCHAR2(200 BYTE),
  CONSTRAINT XX_SCH_REPORT_SETUP_DTL_PK PRIMARY KEY (EI_REP_DTL_ID)
);

CREATE TABLE XX_SCH_REPORT_SETUP_HDR
(
  EI_REP_HEADER_ID    NUMBER                    DEFAULT "XX_SCH_REPORT_HEADER_SEQ"."NEXTVAL" NOT NULL,
  ESS_JOB_NAME        VARCHAR2(100 BYTE),
  REPORT_PATH         VARCHAR2(400 BYTE),
  REPORT_DATA_TABLE   VARCHAR2(50 BYTE),
  REPORT_DATA_FORMAT  VARCHAR2(10 BYTE),
  REPORT_DATA_LOCALE  VARCHAR2(10 BYTE),
  SERVICE_TYPE        VARCHAR2(100 BYTE),
  IS_REFRESH          VARCHAR2(1 BYTE),
  DELIMITER           VARCHAR2(1 BYTE),
  ROOT_NODE           VARCHAR2(100 CHAR),
  SCHEDULER_ID        NUMBER,
  CREATED_BY          VARCHAR2(255 BYTE)        DEFAULT NULL,
  UPDATED_BY          VARCHAR2(255 BYTE)        DEFAULT NULL,
  UPDATED_DATE        DATE                      DEFAULT NULL,
  CREATED_DATE        DATE                      DEFAULT NULL,
  CONSTRAINT XX_SCH_REPORT_SETUP_HDR_PK PRIMARY KEY (EI_REP_HEADER_ID)
);

CREATE TABLE XX_SCH_SCHEDULER_DATE
(
  SCHEDULER_DATE_ID  NUMBER(19)                 DEFAULT "XX_SCH_SCHEDULER_DATE_SEQ"."NEXTVAL" NOT NULL,
  SERVICE_TYPE       VARCHAR2(100 BYTE)         DEFAULT NULL,
  SCHEDULER_FLAG     VARCHAR2(1 BYTE)           DEFAULT NULL,
  SCHEDULER_DATE     TIMESTAMP(0)               DEFAULT SYSTIMESTAMP,
  CREATED_BY         VARCHAR2(255 BYTE)         DEFAULT NULL,
  UPDATED_BY         VARCHAR2(255 BYTE)         DEFAULT NULL,
  UPDATION_DATE      DATE                       DEFAULT SYSTIMESTAMP,
  CREATION_DATE      DATE                       DEFAULT SYSTIMESTAMP,
  SCHEDULER_ID       NUMBER,
  CONSTRAINT XX_SCH_SCHEDULER_DATE_PK PRIMARY KEY (SCHEDULER_DATE_ID)
);

CREATE TABLE XX_SCH_SCHEDULER_SETUP
(
  SCHEDULER_ID      NUMBER(19)                  DEFAULT "XX_SCH_SCHEDULER_SETUP_SEQ"."NEXTVAL" NOT NULL,
  APP_NAME          VARCHAR2(50 BYTE),
  SERVICE_NAME      VARCHAR2(50 BYTE)           DEFAULT NULL,
  START_FLAG        VARCHAR2(1 BYTE)            DEFAULT NULL,
  SCHEDULER_TYPE    VARCHAR2(1 BYTE)            DEFAULT NULL,
  HOUR              NUMBER(19)                  DEFAULT NULL,
  MINUTE            NUMBER(19)                  DEFAULT NULL,
  SECOND            NUMBER(19)                  DEFAULT NULL,
  SERVICE_TYPE      VARCHAR2(100 BYTE)          DEFAULT NULL,
  CREATED_BY        VARCHAR2(255 BYTE)          DEFAULT NULL,
  UPDATED_BY        VARCHAR2(255 BYTE)          DEFAULT NULL,
  UPDATION_DATE     DATE                        DEFAULT NULL,
  CREATION_DATE     DATE                        DEFAULT NULL,
  STATUS            VARCHAR2(100 BYTE)          DEFAULT NULL,
  IS_PARAMETERIZED  VARCHAR2(1 BYTE)            DEFAULT NULL,
  CALL_TYPE         VARCHAR2(5 BYTE)            DEFAULT NULL,
  SCHEDULE_FLAG     VARCHAR2(1 BYTE),
  CONSTRAINT XX_SCH_SCHEDULER_SETUP_PK PRIMARY KEY(SCHEDULER_ID)
);

