package sc.common.model.service;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Dec 04 11:23:13 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class GenericSchedulerAMImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public GenericSchedulerAMImpl() {
    }

    /**
     * Container's getter for SchedulerSetupEOVO1.
     * @return SchedulerSetupEOVO1
     */
    public ViewObjectImpl getSchedulerSetupEOVO1() {
        return (ViewObjectImpl) findViewObject("SchedulerSetupEOVO1");
    }

    /**
     * Container's getter for ReportSetupHeaderEOVO1.
     * @return ReportSetupHeaderEOVO1
     */
    public ViewObjectImpl getReportSetupHeaderEOVO1() {
        return (ViewObjectImpl) findViewObject("ReportSetupHeaderEOVO1");
    }

    /**
     * Container's getter for ReportSetupDetailEOVO1.
     * @return ReportSetupDetailEOVO1
     */
    public ViewObjectImpl getReportSetupDetailEOVO1() {
        return (ViewObjectImpl) findViewObject("ReportSetupDetailEOVO1");
    }

    /**
     * Container's getter for ReportDataMappingEOVO1.
     * @return ReportDataMappingEOVO1
     */
    public ViewObjectImpl getReportDataMappingEOVO1() {
        return (ViewObjectImpl) findViewObject("ReportDataMappingEOVO1");
    }

    /**
     * Container's getter for ReportRunHistoryEOVO1.
     * @return ReportRunHistoryEOVO1
     */
    public ViewObjectImpl getReportRunHistoryEOVO1() {
        return (ViewObjectImpl) findViewObject("ReportRunHistoryEOVO1");
    }

    /**
     * Container's getter for ColumnNameLovVO1.
     * @return ColumnNameLovVO1
     */
    public ViewObjectImpl getColumnNameLovVO1() {
        return (ViewObjectImpl) findViewObject("ColumnNameLovVO1");
    }

    /**
     * Container's getter for SchedulerDateEOVO1.
     * @return SchedulerDateEOVO1
     */
    public ViewObjectImpl getSchedulerDateEOVO1() {
        return (ViewObjectImpl) findViewObject("SchedulerDateEOVO1");
    }

    /**
     * Container's getter for SchedulerSetupToReportHeaderVL1.
     * @return SchedulerSetupToReportHeaderVL1
     */
    public ViewLinkImpl getSchedulerSetupToReportHeaderVL1() {
        return (ViewLinkImpl) findViewLink("SchedulerSetupToReportHeaderVL1");
    }

    /**
     * Container's getter for ReportSetupHeaderTodetailVL1.
     * @return ReportSetupHeaderTodetailVL1
     */
    public ViewLinkImpl getReportSetupHeaderTodetailVL1() {
        return (ViewLinkImpl) findViewLink("ReportSetupHeaderTodetailVL1");
    }

    /**
     * Container's getter for ReportSetupHeaderToDataMappingVL1.
     * @return ReportSetupHeaderToDataMappingVL1
     */
    public ViewLinkImpl getReportSetupHeaderToDataMappingVL1() {
        return (ViewLinkImpl) findViewLink("ReportSetupHeaderToDataMappingVL1");
    }

    /**
     * Container's getter for SchedulerSetupToRunHistoryVL1.
     * @return SchedulerSetupToRunHistoryVL1
     */
    public ViewLinkImpl getSchedulerSetupToRunHistoryVL1() {
        return (ViewLinkImpl) findViewLink("SchedulerSetupToRunHistoryVL1");
    }

    /**
     * Container's getter for SchedulerSetupToSchedulerDateVL1.
     * @return SchedulerSetupToSchedulerDateVL1
     */
    public ViewLinkImpl getSchedulerSetupToSchedulerDateVL1() {
        return (ViewLinkImpl) findViewLink("SchedulerSetupToSchedulerDateVL1");
    }

    /**
     * Container's getter for ExceptionLogVO1.
     * @return ExceptionLogVO1
     */
    public ViewObjectImpl getExceptionLogVO1() {
        return (ViewObjectImpl) findViewObject("ExceptionLogVO1");
    }

    /**
     * Container's getter for ReportRunHistToExceptionLogVL1.
     * @return ReportRunHistToExceptionLogVL1
     */
    public ViewLinkImpl getReportRunHistToExceptionLogVL1() {
        return (ViewLinkImpl) findViewLink("ReportRunHistToExceptionLogVL1");
    }
}

