package sc.common.model.queries;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.server.ViewRowImpl;

import sc.common.model.entities.ReportSetupHeaderEOImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Mar 14 21:31:34 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ReportSetupHeaderEOVORowImpl extends ViewRowImpl {


    public static final int ENTITY_REPORTSETUPHEADEREO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        EiRepHeaderId,
        ReportPath,
        ReportDataTable,
        ReportDataFormat,
        ReportDataLocale,
        CreatedBy,
        CreatedDate,
        UpdatedBy,
        UpdatedDate,
        ServiceType,
        IsRefresh,
        Delimiter,
        RootNode,
        SchedulerId,
        EssJobName,
        ReportSetupDetailEOVO,
        ReportDataMappingEOVO,
        TableListLovVO1,
        DataFormatLovVO1,
        DataLocaleLovVO1,
        YesNoLovVO1,
        DelimiterLovVO1;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int EIREPHEADERID = AttributesEnum.EiRepHeaderId.index();
    public static final int REPORTPATH = AttributesEnum.ReportPath.index();
    public static final int REPORTDATATABLE = AttributesEnum.ReportDataTable.index();
    public static final int REPORTDATAFORMAT = AttributesEnum.ReportDataFormat.index();
    public static final int REPORTDATALOCALE = AttributesEnum.ReportDataLocale.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int UPDATEDBY = AttributesEnum.UpdatedBy.index();
    public static final int UPDATEDDATE = AttributesEnum.UpdatedDate.index();
    public static final int SERVICETYPE = AttributesEnum.ServiceType.index();
    public static final int ISREFRESH = AttributesEnum.IsRefresh.index();
    public static final int DELIMITER = AttributesEnum.Delimiter.index();
    public static final int ROOTNODE = AttributesEnum.RootNode.index();
    public static final int SCHEDULERID = AttributesEnum.SchedulerId.index();
    public static final int ESSJOBNAME = AttributesEnum.EssJobName.index();
    public static final int REPORTSETUPDETAILEOVO = AttributesEnum.ReportSetupDetailEOVO.index();
    public static final int REPORTDATAMAPPINGEOVO = AttributesEnum.ReportDataMappingEOVO.index();
    public static final int TABLELISTLOVVO1 = AttributesEnum.TableListLovVO1.index();
    public static final int DATAFORMATLOVVO1 = AttributesEnum.DataFormatLovVO1.index();
    public static final int DATALOCALELOVVO1 = AttributesEnum.DataLocaleLovVO1.index();
    public static final int YESNOLOVVO1 = AttributesEnum.YesNoLovVO1.index();
    public static final int DELIMITERLOVVO1 = AttributesEnum.DelimiterLovVO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ReportSetupHeaderEOVORowImpl() {
    }

    /**
     * Gets ReportSetupHeaderEO entity object.
     * @return the ReportSetupHeaderEO
     */
    public ReportSetupHeaderEOImpl getReportSetupHeaderEO() {
        return (ReportSetupHeaderEOImpl) getEntity(ENTITY_REPORTSETUPHEADEREO);
    }

    /**
     * Gets the attribute value for EI_REP_HEADER_ID using the alias name EiRepHeaderId.
     * @return the EI_REP_HEADER_ID
     */
    public BigDecimal getEiRepHeaderId() {
        return (BigDecimal) getAttributeInternal(EIREPHEADERID);
    }

    /**
     * Sets <code>value</code> as attribute value for EI_REP_HEADER_ID using the alias name EiRepHeaderId.
     * @param value value to set the EI_REP_HEADER_ID
     */
    public void setEiRepHeaderId(BigDecimal value) {
        setAttributeInternal(EIREPHEADERID, value);
    }

    /**
     * Gets the attribute value for REPORT_PATH using the alias name ReportPath.
     * @return the REPORT_PATH
     */
    public String getReportPath() {
        return (String) getAttributeInternal(REPORTPATH);
    }

    /**
     * Sets <code>value</code> as attribute value for REPORT_PATH using the alias name ReportPath.
     * @param value value to set the REPORT_PATH
     */
    public void setReportPath(String value) {
        setAttributeInternal(REPORTPATH, value);
    }

    /**
     * Gets the attribute value for REPORT_DATA_TABLE using the alias name ReportDataTable.
     * @return the REPORT_DATA_TABLE
     */
    public String getReportDataTable() {
        return (String) getAttributeInternal(REPORTDATATABLE);
    }

    /**
     * Sets <code>value</code> as attribute value for REPORT_DATA_TABLE using the alias name ReportDataTable.
     * @param value value to set the REPORT_DATA_TABLE
     */
    public void setReportDataTable(String value) {
        setAttributeInternal(REPORTDATATABLE, value);
    }

    /**
     * Gets the attribute value for REPORT_DATA_FORMAT using the alias name ReportDataFormat.
     * @return the REPORT_DATA_FORMAT
     */
    public String getReportDataFormat() {
        return (String) getAttributeInternal(REPORTDATAFORMAT);
    }

    /**
     * Sets <code>value</code> as attribute value for REPORT_DATA_FORMAT using the alias name ReportDataFormat.
     * @param value value to set the REPORT_DATA_FORMAT
     */
    public void setReportDataFormat(String value) {
        setAttributeInternal(REPORTDATAFORMAT, value);
    }

    /**
     * Gets the attribute value for REPORT_DATA_LOCALE using the alias name ReportDataLocale.
     * @return the REPORT_DATA_LOCALE
     */
    public String getReportDataLocale() {
        return (String) getAttributeInternal(REPORTDATALOCALE);
    }

    /**
     * Sets <code>value</code> as attribute value for REPORT_DATA_LOCALE using the alias name ReportDataLocale.
     * @param value value to set the REPORT_DATA_LOCALE
     */
    public void setReportDataLocale(String value) {
        setAttributeInternal(REPORTDATALOCALE, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATED_DATE using the alias name CreatedDate.
     * @return the CREATED_DATE
     */
    public Timestamp getCreatedDate() {
        return (Timestamp) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_DATE using the alias name CreatedDate.
     * @param value value to set the CREATED_DATE
     */
    public void setCreatedDate(Timestamp value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for UPDATED_BY using the alias name UpdatedBy.
     * @return the UPDATED_BY
     */
    public String getUpdatedBy() {
        return (String) getAttributeInternal(UPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for UPDATED_BY using the alias name UpdatedBy.
     * @param value value to set the UPDATED_BY
     */
    public void setUpdatedBy(String value) {
        setAttributeInternal(UPDATEDBY, value);
    }

    /**
     * Gets the attribute value for UPDATED_DATE using the alias name UpdatedDate.
     * @return the UPDATED_DATE
     */
    public Timestamp getUpdatedDate() {
        return (Timestamp) getAttributeInternal(UPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for UPDATED_DATE using the alias name UpdatedDate.
     * @param value value to set the UPDATED_DATE
     */
    public void setUpdatedDate(Timestamp value) {
        setAttributeInternal(UPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for SERVICE_TYPE using the alias name ServiceType.
     * @return the SERVICE_TYPE
     */
    public String getServiceType() {
        return (String) getAttributeInternal(SERVICETYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for SERVICE_TYPE using the alias name ServiceType.
     * @param value value to set the SERVICE_TYPE
     */
    public void setServiceType(String value) {
        setAttributeInternal(SERVICETYPE, value);
    }

    /**
     * Gets the attribute value for IS_REFRESH using the alias name IsRefresh.
     * @return the IS_REFRESH
     */
    public String getIsRefresh() {
        return (String) getAttributeInternal(ISREFRESH);
    }

    /**
     * Sets <code>value</code> as attribute value for IS_REFRESH using the alias name IsRefresh.
     * @param value value to set the IS_REFRESH
     */
    public void setIsRefresh(String value) {
        setAttributeInternal(ISREFRESH, value);
    }

    /**
     * Gets the attribute value for DELIMITER using the alias name Delimiter.
     * @return the DELIMITER
     */
    public String getDelimiter() {
        return (String) getAttributeInternal(DELIMITER);
    }

    /**
     * Sets <code>value</code> as attribute value for DELIMITER using the alias name Delimiter.
     * @param value value to set the DELIMITER
     */
    public void setDelimiter(String value) {
        setAttributeInternal(DELIMITER, value);
    }

    /**
     * Gets the attribute value for ROOT_NODE using the alias name RootNode.
     * @return the ROOT_NODE
     */
    public String getRootNode() {
        return (String) getAttributeInternal(ROOTNODE);
    }

    /**
     * Sets <code>value</code> as attribute value for ROOT_NODE using the alias name RootNode.
     * @param value value to set the ROOT_NODE
     */
    public void setRootNode(String value) {
        setAttributeInternal(ROOTNODE, value);
    }

    /**
     * Gets the attribute value for SCHEDULER_ID using the alias name SchedulerId.
     * @return the SCHEDULER_ID
     */
    public BigDecimal getSchedulerId() {
        return (BigDecimal) getAttributeInternal(SCHEDULERID);
    }

    /**
     * Sets <code>value</code> as attribute value for SCHEDULER_ID using the alias name SchedulerId.
     * @param value value to set the SCHEDULER_ID
     */
    public void setSchedulerId(BigDecimal value) {
        setAttributeInternal(SCHEDULERID, value);
    }

    /**
     * Gets the attribute value for ESS_JOB_NAME using the alias name EssJobName.
     * @return the ESS_JOB_NAME
     */
    public String getEssJobName() {
        return (String) getAttributeInternal(ESSJOBNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for ESS_JOB_NAME using the alias name EssJobName.
     * @param value value to set the ESS_JOB_NAME
     */
    public void setEssJobName(String value) {
        setAttributeInternal(ESSJOBNAME, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link ReportSetupDetailEOVO.
     */
    public RowIterator getReportSetupDetailEOVO() {
        return (RowIterator) getAttributeInternal(REPORTSETUPDETAILEOVO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link ReportDataMappingEOVO.
     */
    public RowIterator getReportDataMappingEOVO() {
        return (RowIterator) getAttributeInternal(REPORTDATAMAPPINGEOVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> TableListLovVO1.
     */
    public RowSet getTableListLovVO1() {
        return (RowSet) getAttributeInternal(TABLELISTLOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> DataFormatLovVO1.
     */
    public RowSet getDataFormatLovVO1() {
        return (RowSet) getAttributeInternal(DATAFORMATLOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> DataLocaleLovVO1.
     */
    public RowSet getDataLocaleLovVO1() {
        return (RowSet) getAttributeInternal(DATALOCALELOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> YesNoLovVO1.
     */
    public RowSet getYesNoLovVO1() {
        return (RowSet) getAttributeInternal(YESNOLOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> DelimiterLovVO1.
     */
    public RowSet getDelimiterLovVO1() {
        return (RowSet) getAttributeInternal(DELIMITERLOVVO1);
    }


}

