
package sc.common.biReport;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 *
 */
@WebFault(name = "fault", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
public class AccessDeniedException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private AccessDeniedException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public AccessDeniedException_Exception(String message, AccessDeniedException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public AccessDeniedException_Exception(String message, AccessDeniedException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: sc.common.biReport.AccessDeniedException
     */
    public AccessDeniedException getFaultInfo() {
        return faultInfo;
    }

}
