package sc.common.model.queries.common;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Mar 14 21:31:59 IST 2019
// ---------------------------------------------------------------------
public interface ReportSetupDetailEOVORow extends Row {
    BigDecimal getEiRepDtlId();

    void setEiRepDtlId(BigDecimal value);

    BigDecimal getEiRepHeaderId();

    void setEiRepHeaderId(BigDecimal value);

    String getParamName();

    void setParamName(String value);

    String getParamSqlType();

    void setParamSqlType(String value);

    String getDefualtVal();

    void setDefualtVal(String value);

    String getLastValLookupType();

    void setLastValLookupType(String value);

    String getCreatedBy();

    void setCreatedBy(String value);

    Timestamp getCreatedDate();

    void setCreatedDate(Timestamp value);

    String getUpdatedBy();

    void setUpdatedBy(String value);

    Timestamp getUpdatedDate();

    void setUpdatedDate(Timestamp value);

    String getSqlStatement();

    void setSqlStatement(String value);
}

