package sc.common.model.entities;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.SequenceImpl;
import oracle.jbo.server.TransactionEvent;

import sc.common.model.util.ObjectConversion;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Apr 04 16:36:40 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SchedulerSetupEOImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        SchedulerId,
        ServiceName,
        SchedulerType,
        Hour,
        Minute,
        Second,
        ServiceType,
        CreatedBy,
        UpdatedBy,
        UpdationDate,
        CreationDate,
        Status,
        IsParameterized,
        CallType,
        ScheduleFlag,
        AppName;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int SCHEDULERID = AttributesEnum.SchedulerId.index();
    public static final int SERVICENAME = AttributesEnum.ServiceName.index();
    public static final int SCHEDULERTYPE = AttributesEnum.SchedulerType.index();
    public static final int HOUR = AttributesEnum.Hour.index();
    public static final int MINUTE = AttributesEnum.Minute.index();
    public static final int SECOND = AttributesEnum.Second.index();
    public static final int SERVICETYPE = AttributesEnum.ServiceType.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int UPDATEDBY = AttributesEnum.UpdatedBy.index();
    public static final int UPDATIONDATE = AttributesEnum.UpdationDate.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int ISPARAMETERIZED = AttributesEnum.IsParameterized.index();
    public static final int CALLTYPE = AttributesEnum.CallType.index();
    public static final int SCHEDULEFLAG = AttributesEnum.ScheduleFlag.index();
    public static final int APPNAME = AttributesEnum.AppName.index();

    /**
     * This is the default constructor (do not remove).
     */
    public SchedulerSetupEOImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("sc.common.model.entities.SchedulerSetupEO");
    }


    /**
     * Gets the attribute value for SchedulerId, using the alias name SchedulerId.
     * @return the value of SchedulerId
     */
    public BigDecimal getSchedulerId() {
        return (BigDecimal) getAttributeInternal(SCHEDULERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SchedulerId.
     * @param value value to set the SchedulerId
     */
    public void setSchedulerId(BigDecimal value) {
        setAttributeInternal(SCHEDULERID, value);
    }

    /**
     * Gets the attribute value for ServiceName, using the alias name ServiceName.
     * @return the value of ServiceName
     */
    public String getServiceName() {
        return (String) getAttributeInternal(SERVICENAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for ServiceName.
     * @param value value to set the ServiceName
     */
    public void setServiceName(String value) {
        setAttributeInternal(SERVICENAME, value);
    }

   
    /**
     * Gets the attribute value for SchedulerType, using the alias name SchedulerType.
     * @return the value of SchedulerType
     */
    public String getSchedulerType() {
        return (String) getAttributeInternal(SCHEDULERTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for SchedulerType.
     * @param value value to set the SchedulerType
     */
    public void setSchedulerType(String value) {
        setAttributeInternal(SCHEDULERTYPE, value);
    }

    /**
     * Gets the attribute value for Hour, using the alias name Hour.
     * @return the value of Hour
     */
    public BigDecimal getHour() {
        return (BigDecimal) getAttributeInternal(HOUR);
    }

    /**
     * Sets <code>value</code> as the attribute value for Hour.
     * @param value value to set the Hour
     */
    public void setHour(BigDecimal value) {
        setAttributeInternal(HOUR, value);
    }

    /**
     * Gets the attribute value for Minute, using the alias name Minute.
     * @return the value of Minute
     */
    public BigDecimal getMinute() {
        return (BigDecimal) getAttributeInternal(MINUTE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Minute.
     * @param value value to set the Minute
     */
    public void setMinute(BigDecimal value) {
        setAttributeInternal(MINUTE, value);
    }

    /**
     * Gets the attribute value for Second, using the alias name Second.
     * @return the value of Second
     */
    public BigDecimal getSecond() {
        return (BigDecimal) getAttributeInternal(SECOND);
    }

    /**
     * Sets <code>value</code> as the attribute value for Second.
     * @param value value to set the Second
     */
    public void setSecond(BigDecimal value) {
        setAttributeInternal(SECOND, value);
    }

    /**
     * Gets the attribute value for ServiceType, using the alias name ServiceType.
     * @return the value of ServiceType
     */
    public String getServiceType() {
        return (String) getAttributeInternal(SERVICETYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ServiceType.
     * @param value value to set the ServiceType
     */
    public void setServiceType(String value) {
        setAttributeInternal(SERVICETYPE, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for UpdatedBy, using the alias name UpdatedBy.
     * @return the value of UpdatedBy
     */
    public String getUpdatedBy() {
        return (String) getAttributeInternal(UPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpdatedBy.
     * @param value value to set the UpdatedBy
     */
    public void setUpdatedBy(String value) {
        setAttributeInternal(UPDATEDBY, value);
    }

    /**
     * Gets the attribute value for UpdationDate, using the alias name UpdationDate.
     * @return the value of UpdationDate
     */
    public Timestamp getUpdationDate() {
        return (Timestamp) getAttributeInternal(UPDATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpdationDate.
     * @param value value to set the UpdationDate
     */
    public void setUpdationDate(Timestamp value) {
        setAttributeInternal(UPDATIONDATE, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the value of CreationDate
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreationDate.
     * @param value value to set the CreationDate
     */
    public void setCreationDate(Timestamp value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for Status, using the alias name Status.
     * @return the value of Status
     */
    public String getStatus() {
        return (String) getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Status.
     * @param value value to set the Status
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * Gets the attribute value for IsParameterized, using the alias name IsParameterized.
     * @return the value of IsParameterized
     */
    public String getIsParameterized() {
        return (String) getAttributeInternal(ISPARAMETERIZED);
    }

    /**
     * Sets <code>value</code> as the attribute value for IsParameterized.
     * @param value value to set the IsParameterized
     */
    public void setIsParameterized(String value) {
        setAttributeInternal(ISPARAMETERIZED, value);
    }

    /**
     * Gets the attribute value for CallType, using the alias name CallType.
     * @return the value of CallType
     */
    public String getCallType() {
        return (String) getAttributeInternal(CALLTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CallType.
     * @param value value to set the CallType
     */
    public void setCallType(String value) {
        setAttributeInternal(CALLTYPE, value);
    }


    /**
     * Gets the attribute value for ScheduleFlag, using the alias name ScheduleFlag.
     * @return the value of ScheduleFlag
     */
    public String getScheduleFlag() {
        return (String) getAttributeInternal(SCHEDULEFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for ScheduleFlag.
     * @param value value to set the ScheduleFlag
     */
    public void setScheduleFlag(String value) {
        setAttributeInternal(SCHEDULEFLAG, value);
    }


    /**
     * Gets the attribute value for AppName, using the alias name AppName.
     * @return the value of AppName
     */
    public String getAppName() {
        return (String) getAttributeInternal(APPNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for AppName.
     * @param value value to set the AppName
     */
    public void setAppName(String value) {
        setAttributeInternal(APPNAME, value);
    }

    /**
     * @param schedulerId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(BigDecimal schedulerId) {
        return new Key(new Object[] { schedulerId });
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        SequenceImpl seq = new SequenceImpl("XX_SCH_SCHEDULER_SETUP_SEQ", getDBTransaction());
        try {
            setSchedulerId(ObjectConversion.convertNumberToBigDecimal(seq.getSequenceNumber()));
            setScheduleFlag("N");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        super.doDML(operation, e);
    }
}

