package sc.common.model.queries.common;

import java.math.BigDecimal;
import java.math.BigInteger;

import oracle.jbo.Row;
import oracle.jbo.domain.BlobDomain;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Mar 14 21:32:15 IST 2019
// ---------------------------------------------------------------------
public interface ReportDataMappingEOVORow extends Row {
    BigDecimal getMapId();

    void setMapId(BigDecimal value);

    String getReportColName();

    void setReportColName(String value);

    Long getReportSeqName();

    void setReportSeqName(Long value);

    String getTableColName();

    void setTableColName(String value);

    String getDefaultValue();

    void setDefaultValue(String value);

    BigDecimal getReportHeaderId();

    void setReportHeaderId(BigDecimal value);

    String getPrimaryFlag();

    void setPrimaryFlag(String value);
}

