
package sc.common.biReport;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PublicReportServiceService", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", wsdlLocation = "https://elzx-dev1.fa.em2.oraclecloud.com/xmlpserver/services/PublicReportService?WSDL")
public class PublicReportServiceService
    extends Service
{

    private final static URL PUBLICREPORTSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException PUBLICREPORTSERVICESERVICE_EXCEPTION;
    private final static QName PUBLICREPORTSERVICESERVICE_QNAME = new QName("http://xmlns.oracle.com/oxp/service/PublicReportService", "PublicReportServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://elzx-dev1.fa.em2.oraclecloud.com/xmlpserver/services/PublicReportService?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PUBLICREPORTSERVICESERVICE_WSDL_LOCATION = url;
        PUBLICREPORTSERVICESERVICE_EXCEPTION = e;
    }

    public PublicReportServiceService() {
        super(__getWsdlLocation(), PUBLICREPORTSERVICESERVICE_QNAME);
    }

    public PublicReportServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PUBLICREPORTSERVICESERVICE_QNAME, features);
    }

    public PublicReportServiceService(URL wsdlLocation) {
        super(wsdlLocation, PUBLICREPORTSERVICESERVICE_QNAME);
    }

    public PublicReportServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PUBLICREPORTSERVICESERVICE_QNAME, features);
    }

    public PublicReportServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PublicReportServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PublicReportService
     */
    @WebEndpoint(name = "PublicReportService")
    public PublicReportService getPublicReportService() {
        return super.getPort(new QName("http://xmlns.oracle.com/oxp/service/PublicReportService", "PublicReportService"), PublicReportService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PublicReportService
     */
    @WebEndpoint(name = "PublicReportService")
    public PublicReportService getPublicReportService(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/oxp/service/PublicReportService", "PublicReportService"), PublicReportService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PUBLICREPORTSERVICESERVICE_EXCEPTION!= null) {
            throw PUBLICREPORTSERVICESERVICE_EXCEPTION;
        }
        return PUBLICREPORTSERVICESERVICE_WSDL_LOCATION;
    }

}
