--------------------------------------------------------
--  DDL for Table XX_SCH_EXCEPTION_LOG
--------------------------------------------------------

  CREATE TABLE "XX_SCH_EXCEPTION_LOG" 
   (	"EXCEPTION_ID" NUMBER, 
	"BEAN_NAME" VARCHAR2(100), 
	"METHOD_NAME" VARCHAR2(100), 
	"ERROR_MESSAGE" CLOB, 
	"CREATED_DATETIME" TIMESTAMP (6) DEFAULT SYSDATE, 
	"CREATED_BY" VARCHAR2(50), 
	"JOB_ID" VARCHAR2(100 CHAR)
   )
--------------------------------------------------------
--  DDL for Table XX_SCH_LOOKUP_STRINGS
--------------------------------------------------------

  CREATE TABLE "XX_SCH_LOOKUP_STRINGS" 
   (	"GEN_ID" NUMBER, 
	"TYPE" VARCHAR2(100), 
	"CODE" VARCHAR2(100), 
	"VALUE" VARCHAR2(100), 
	"ENT_DATE" DATE, 
	"ENT_BY" VARCHAR2(100), 
	"MODIFY_BY" VARCHAR2(100), 
	"MODIFY_DATE" DATE, 
	"ENABLE_FLAG" VARCHAR2(1)
   )
--------------------------------------------------------
--  DDL for Table XX_SCH_REPORT_DATA_MAPPING
--------------------------------------------------------

  CREATE TABLE "XX_SCH_REPORT_DATA_MAPPING" 
   (	"MAP_ID" NUMBER(19,0), 
	"REPORT_COL_NAME" VARCHAR2(200) DEFAULT NULL, 
	"REPORT_SEQ_NAME" NUMBER(10,0) DEFAULT NULL, 
	"TABLE_COL_NAME" VARCHAR2(200) DEFAULT NULL, 
	"DEFAULT_VALUE" VARCHAR2(200) DEFAULT NULL, 
	"REPORT_HEADER_ID" NUMBER(19,0) DEFAULT NULL, 
	"PRIMARY_FLAG" VARCHAR2(10) DEFAULT NULL, 
	"DATE_FORMAT" VARCHAR2(50 CHAR), 
	"IS_SEQ" VARCHAR2(1), 
	"COLUMN_DATA_TYPE" VARCHAR2(100 CHAR)
   )
--------------------------------------------------------
--  DDL for Table XX_SCH_REPORT_RUN_HIS
--------------------------------------------------------

  CREATE TABLE "XX_SCH_REPORT_RUN_HIS" 
   (	"ID" NUMBER, 
	"SERVICE_TYPE" VARCHAR2(100 CHAR), 
	"STATUS" VARCHAR2(50 CHAR), 
	"RECORD_PROCESSED" VARCHAR2(100 CHAR), 
	"START_TIME" TIMESTAMP (6) DEFAULT SYSDATE, 
	"END_TME" TIMESTAMP (6), 
	"RUN_TYPE" VARCHAR2(50), 
	"SCHEDULER_ID" NUMBER
   )
--------------------------------------------------------
--  DDL for Table XX_SCH_REPORT_SETUP_DTL
--------------------------------------------------------

  CREATE TABLE "XX_SCH_REPORT_SETUP_DTL" 
   (	"EI_REP_DTL_ID" NUMBER, 
	"EI_REP_HEADER_ID" NUMBER, 
	"PARAM_NAME" VARCHAR2(50), 
	"PARAM_SQL_TYPE" VARCHAR2(50), 
	"DEFUALT_VAL" VARCHAR2(50), 
	"LAST_VAL_LOOKUP_TYPE" VARCHAR2(50), 
	"CREATED_BY" VARCHAR2(100), 
	"CREATED_DATE" DATE, 
	"UPDATED_BY" VARCHAR2(100), 
	"UPDATED_DATE" DATE, 
	"SQL_STATEMENT" VARCHAR2(200)
   )
--------------------------------------------------------
--  DDL for Table XX_SCH_REPORT_SETUP_HDR
--------------------------------------------------------

  CREATE TABLE "XX_SCH_REPORT_SETUP_HDR" 
   (	"EI_REP_HEADER_ID" NUMBER DEFAULT "XX_SCH_REPORT_HEADER_SEQ"."NEXTVAL", 
	"ESS_JOB_NAME" VARCHAR2(100), 
	"REPORT_PATH" VARCHAR2(400), 
	"REPORT_DATA_TABLE" VARCHAR2(50), 
	"REPORT_DATA_FORMAT" VARCHAR2(10), 
	"REPORT_DATA_LOCALE" VARCHAR2(10), 
	"SERVICE_TYPE" VARCHAR2(100), 
	"IS_REFRESH" VARCHAR2(1), 
	"DELIMITER" VARCHAR2(1), 
	"ROOT_NODE" VARCHAR2(100 CHAR), 
	"SCHEDULER_ID" NUMBER, 
	"CREATED_BY" VARCHAR2(255) DEFAULT NULL, 
	"UPDATED_BY" VARCHAR2(255) DEFAULT NULL, 
	"UPDATED_DATE" DATE DEFAULT NULL, 
	"CREATED_DATE" DATE DEFAULT NULL
   )
--------------------------------------------------------
--  DDL for Table XX_SCH_SCHEDULER_DATE
--------------------------------------------------------

  CREATE TABLE "XX_SCH_SCHEDULER_DATE" 
   (	"SCHEDULER_DATE_ID" NUMBER, 
	"SERVICE_TYPE" VARCHAR2(100), 
	"SCHEDULER_FLAG" VARCHAR2(1), 
	"SCHEDULER_DATE" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(255), 
	"UPDATED_BY" VARCHAR2(255), 
	"UPDATION_DATE" DATE, 
	"CREATION_DATE" DATE, 
	"SCHEDULER_ID" NUMBER
   )
--------------------------------------------------------
--  DDL for Table XX_SCH_SCHEDULER_SETUP
--------------------------------------------------------

  CREATE TABLE "XX_SCH_SCHEDULER_SETUP" 
   (	"SCHEDULER_ID" NUMBER(19,0) DEFAULT "XX_SCH_SCHEDULER_SETUP_SEQ"."NEXTVAL", 
	"APP_NAME" VARCHAR2(50), 
	"SERVICE_NAME" VARCHAR2(50) DEFAULT NULL, 
	"START_FLAG" VARCHAR2(1) DEFAULT NULL, 
	"SCHEDULER_TYPE" VARCHAR2(1) DEFAULT NULL, 
	"HOUR" NUMBER(19,0) DEFAULT NULL, 
	"MINUTE" NUMBER(19,0) DEFAULT NULL, 
	"SECOND" NUMBER(19,0) DEFAULT NULL, 
	"SERVICE_TYPE" VARCHAR2(100) DEFAULT NULL, 
	"CREATED_BY" VARCHAR2(255) DEFAULT NULL, 
	"UPDATED_BY" VARCHAR2(255) DEFAULT NULL, 
	"UPDATION_DATE" DATE DEFAULT NULL, 
	"CREATION_DATE" DATE DEFAULT NULL, 
	"STATUS" VARCHAR2(100) DEFAULT NULL, 
	"IS_PARAMETERIZED" VARCHAR2(1) DEFAULT NULL, 
	"CALL_TYPE" VARCHAR2(5) DEFAULT NULL, 
	"SCHEDULE_FLAG" VARCHAR2(1)
   )
--------------------------------------------------------
--  DDL for Table XXZATCA_INVOICE_FILES
--------------------------------------------------------

  CREATE TABLE "XXZATCA_INVOICE_FILES" 
   (	"TRANSACTION_ID" VARCHAR2(1000), 
	"INVOICE_FILE" BLOB, 
	"COMPANY" VARCHAR2(100) DEFAULT 'HULOOL', 
	"PDFA3" BLOB, 
	"CUSTOMER_TRX_ID" VARCHAR2(1000)
   )
--------------------------------------------------------
--  DDL for Table XX_PAAS_SETUP_DTL
--------------------------------------------------------

  CREATE TABLE "XX_PAAS_SETUP_DTL" 
   (	"SETUP_ID" NUMBER DEFAULT NULL, 
	"HOST" VARCHAR2(1000), 
	"PORT" VARCHAR2(10), 
	"USER_NAME" VARCHAR2(100), 
	"PASSWORD" VARCHAR2(1000), 
	"SETUP_TYPE" VARCHAR2(50), 
	"SUB_TYPE" VARCHAR2(50), 
	"OPERATION" VARCHAR2(10), 
	"ENT_DATE" DATE DEFAULT SYSDATE, 
	"ENT_BY" VARCHAR2(50), 
	"MODIFY_BY" VARCHAR2(50), 
	"MODIFY_DATE" DATE DEFAULT SYSDATE, 
	"SFTP_PATH" VARCHAR2(1000), 
	"MODULE" VARCHAR2(100), 
	"EMAIL_ADDRESS" VARCHAR2(1000), 
	"ABC" NUMBER(*,0)
   )
